version: '2'

services:
  shms-frontend:
    build:
      context: ./SHMS-frontend
      dockerfile: Dockerfile
    container_name: shms-frontend
    ports:
      - "4200:80" # Expose the Angular app on port 4200
  
  shms-service:
    build:
      context: ./SHMS
      dockerfile: Dockerfile
    container_name: shms-service
    ports:
      - "9090:9090"
    depends_on:
      - postgresql
    environment:
      - APPLICATION_NAME=shms-service
      - APPLICATION_PORT=9090
      - APPLICATION_SSL=false
      - DATABASE_PASSWORD=1
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/shms_db
      - DATABASE_USER=shms_dev
      - EUREKA_HOST=discovery-service
      - EUREKA_PORT=8761
      - EUREKA_SCHEME=http
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=shms_dev
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=shms_db
    ports:
      - "5432:5432"
  
  discovery-service:
    build:
      context: ./Discovery
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761" # Spring Boot Discovery Service (Eureka)
    environment:
      - EUREKA_INSTANCE_HOSTNAME=discovery-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    restart: always